# Generated by Django 5.0.1 on 2024-01-27 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Wallet_address', models.CharField(max_length=256)),
                ('Email_Id', models.EmailField(max_length=254)),
                ('Name', models.CharField(max_length=256)),
                ('Age', models.IntegerField()),
                ('Password', models.CharField(max_length=256)),
                ('Phone_Number', models.IntegerField()),
                ('Address', models.CharField(max_length=256)),
                ('City', models.CharField(max_length=256)),
                ('Aadhar_card_doc', models.FileField(upload_to='static/uploads/user_aadhar/')),
                ('Pan_card_doc', models.FileField(upload_to='static/uploads/user_pan/')),
                ('Profile_Photo', models.FileField(upload_to='static/uploads/user_profile/')),
            ],
        ),
    ]
