# Generated by Django 5.0.1 on 2024-01-27 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_data',
            name='Email_Verified',
            field=models.BooleanField(default=True),
        ),
    ]
