# Generated by Django 5.0.1 on 2024-01-27 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Add_property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('long', models.FloatField()),
                ('survey_no', models.IntegerField()),
                ('wallet_address', models.CharField(max_length=256)),
                ('property_id', models.IntegerField()),
                ('document', models.FileField(upload_to='static/uploads/doc_property/')),
                ('Date', models.TextField()),
                ('Total_Owners', models.IntegerField()),
                ('status', models.CharField(max_length=256)),
            ],
        ),
    ]
